version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requierements.txt
  pre_build:
    commands:
      - echo start pre-build and end Installing
  
  build:
    commands:
      - echo Build phase...
      - pytest --junitxml=test-results.xml --tb=short
  post_build:
    commands:
      - echo build completed successfully

artifacts:
  files:
    - '**/*'
  base-directory: 
reports:
  pytest-report:
    files:
      - "reports/results.xml"
    discards-paths: yes
    